### PR TITLE
CIFAR cleaning and better plotting

### PR DESCRIPTION
**Pull request by Atcold**
Removed unnecessary requirements and merged accuracy graphs for `train-on-cifar`

### CODE REVIEW

**Comment by Atcold** [comment]
Perhaps new commits will come... Do not merge it yet.

**Comment by Atcold** [comment]
Both train and test accuracy on the same chart
ac
Error plots show when overfitting is occuring
er

**Comment by Atcold** [comment]
It should be "mergeable" now :+1:

**Comment by soumith** [comment]
slick!

**Pull request merged**
